meta_product_name: "Seety"
meta_title: "Seety - L'application qui te fait visiter la France !"
meta_description: "Seety vous permet de construire vous-mêmes votre itinéraire à travers les grandes villes françaises !"
meta_image: "fond.jpeg"
